## 1,2,3 Dimensional Matrix

In [52]:
import numpy as np

n1 = np.empty (1, dtype = int)
print("Matrix n1 : \n", n1) 

n2 = np.empty([2, 2], dtype = int)
print("\n Matrix n2 : \n", n2)

n3 = np.empty([3, 3],dtype = int)
print("\n Matrix n3 : \n", n3)

Matrix n1 : 
 [0]

 Matrix n2 : 
 [[55  6]
 [ 7  8]]

 Matrix n3 : 
 [[      0       1       0]
 [    658    1272       0]
 [    768     658 7667816]]


## Addition of Matrices

In [16]:
z=np.zeros([2,2] ,dtype=int)
print("Matrix of z: \n",z)

Matrix of z: 
 [[0 0]
 [0 0]]


In [21]:
n1= np.array ([1,2,3,4])
n2= np.array ([5,6,7,8])
n3= np.add (n1,n2)
print ("Matrix of n3:\n" ,n3)

Matrix of n3:
 [ 6  8 10 12]


In [23]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

[  8  79  26 134]


## Subtraction of Matrices

In [36]:
n1= np.array ([8,12,13,14])
n2= np.array ([55,6,7,8])
n3= n1-n2
print ("Matrix of n3:\n" ,n3)

Matrix of n3:
 [-47   6   6   6]


In [32]:
n1 = np.array([8, 12, 13, 14])
n2 = np.array([5, 6, 7, 8])
n3 = n1 - n2
print("Matrix of n3:\n", n3)


Matrix of n3:
 [3 6 6 6]


## Multiplication of Matrices

In [37]:
n1= np.array ([8,12,13,14])
n2= np.array ([55,6,7,8])
n3= n1*n2
print ("Multiplication Matrix of n3:\n" ,n3)

Multiplication Matrix of n3:
 [440  72  91 112]


In [38]:
n1= np.array ([8,12,13,14])
n2= np.array ([55,6,7,8])
n3= np.multiply(n1,n2)
print ("Multiplication Matrix of n3:\n" ,n3)

Multiplication Matrix of n3:
 [440  72  91 112]


In [ ]:
## Division of Matrices

In [47]:
n1= np.array ([8,12,13,14],dtype = int)
n2= np.array ([55,6,7,8], dtype = int)
n3= np.divide(n1,n2)
np.set_printoptions(precision=2, suppress=True)
print ("Division Matrix of n3:\n" ,n3)

Division Matrix of n3:
 [0.15 2.   1.86 1.75]


In [48]:
n1= np.array ([8,12,13,14],dtype = int)
n2= np.array ([55,6,7,8], dtype = int)
n3= n1/n2
np.set_printoptions(precision=2, suppress=True)
print ("Division Matrix of n3:\n" ,n3)

Division Matrix of n3:
 [0.15 2.   1.86 1.75]
