## Indexing

In [8]:
import numpy as np
n1 = np.arange (10,-9,-3) #10 --> The Starting Value,
                          #-3 -->The Step Value,
                          #-9 --> The End Value (Exclusive*)
print ("The output is : \n", n1)

The output is : 
 [10  7  4  1 -2 -5 -8]


In [43]:
n1 = np.arange (10,-9,-3)
#n2 =np.arange(3,-2,-1) -- we get a result of [ 3  2  1  0 -1] just replace those index values with the original values of n1
#for example 3 - 1, 2-4 , 1- 7, 0-10 & -1-(-8)
print(n3)
n2 = n1[np.arange (3,-2,-1)]
print ("The Value of n2:\n" ,n2)

[ 3  2  1  0 -1]
The Value of n2:
 [ 1  4  7 10 -8]


## Slicing

In [32]:
n1 = np.arange(20)
print(n1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [47]:
n1 = np.arange(20)
print("Value of n1:\n" ,n1)
n1[-8:13:6] # Modifying elements in the specified slice

print("Value of [-8:13:6]:\n" ,n1[-5:19:1]) # -5 Start
                   # 19 Step
                   #1 Stop 
print ("Value of [10:]:\n" ,n1[10:])

Value of n1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Value of [-8:13:6]:
 [15 16 17 18]
Value of [10:]:
 [10 11 12 13 14 15 16 17 18 19]


In [72]:
n1 = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]]])
print("1st Method to get n1 :\n" ,n1[...,1]) #... Excluding 
print("2nd Method to get n1 :\n", n1)


1st Method to get n1 :
 [[ 2  5]
 [ 8 11]]
2nd Method to get n1 :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Broadcasting of Numpy
## Broadcasting of 1 Array
Note: NumPy broadcasting allows for element-wise operations between arrays of different shapes and sizes, implicitly extending dimensions to make them compatible for efficient computation.

In [83]:
n1 = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9], 
              [10, 11, 12]])
n2= np.zeros_like(n1) # Creating a new array filled with 0's
n3= np.array ([13,14,15])
for i in range (n1.shape[0]):#Element-Wise Multiplication in a Loop
    n2 [i,:] = n1[i,:]* n3

n2

array([[ 13,  28,  45],
       [ 52,  70,  90],
       [ 91, 112, 135],
       [130, 154, 180]])